title: "Ruiting Liang"
description: "personal webpage of RL"
remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-remote-theme
url: "https://ruitingl.github.io"
baseurl: ""
# Optional:
show_downloads: false           # true shows a download link if the theme supports it
google_analytics:               # (leave blank if you don't use GA)
